Config.Weapons = {
	--MELE
	{name = 'WEAPON_DAGGER', label = _U('weapon_dagger'), components = {}},
	{name = 'WEAPON_BAT', label = _U('weapon_bat'), components = {}},
	{name = 'WEAPON_BOTTLE', label = _U('weapon_bottle'), components = {}},
	{name = 'WEAPON_CROWBAR', label = _U('weapon_crowbar'), components = {}},
	{name = 'WEAPON_FLASHLIGHT', label = _U('weapon_flashlight'), components = {}},
	{name = 'WEAPON_GOLFCLUB', label = _U('weapon_golfclub'), components = {}},
	{name = 'WEAPON_HAMMER', label = _U('weapon_hammer'), components = {}},
	{name = 'WEAPON_HATCHET', label = _U('weapon_hatchet'), components = {}},
	{
		name = 'WEAPON_KNUCKLE',
		label = _U('weapon_knuckle'),
		components = {
			{name = 'kastet_baza', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_BASE')},
			{name = 'kastet_pimp', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_PIMP')},
			{name = 'kastet_ballas', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_BALLAS')},
			{name = 'kastet_dolar', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_DOLLAR')},
			{name = 'kastet_diament', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_DIAMOND')},
			{name = 'kastet_nienawiść', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_HATE')},
			{name = 'kastet_miłość', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_LOVE')},
			{name = 'kastet_gracz', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_PLAYER')},
			{name = 'kastet_król', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_KING')},
			{name = 'kastet_vagos', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_KNUCKLE_VARMOD_VAGOS')},
		}
	},
	{name = 'WEAPON_KNIFE', label = _U('weapon_knife'), components = {}},
	{name = 'WEAPON_MACHETE', label = _U('weapon_machete'), components = {}},
	{name = 'WEAPON_SWITCHBLADE', label = _U('weapon_switchblade'), components = {}},
	{name = 'WEAPON_NIGHTSTICK', label = _U('weapon_nightstick'), components = {}},
	{name = 'WEAPON_WRENCH', label = _U('weapon_wrench'), components = {}},
	{name = 'WEAPON_BATTLEAXE', label = _U('weapon_battleaxe'), components = {}},
	{name = 'WEAPON_POOLCUE', label = _U('weapon_poolcue'), components = {}},
	{name = 'WEAPON_STONE_HATCHET', label = _U('weapon_stone_hatchet'), components = {}},
	--PISTOLS
	{
		name = 'WEAPON_PISTOL',
		label = _U('weapon_pistol'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_PISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_PISTOL_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP_02')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_PISTOL_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_PISTOL_MK2',
		label = _U('weapon_pistol_mk2'),
		components = {
			{name = 'hamulec_wylotowy', label = _U('component_compensator'), hash = GetHashKey('COMPONENT_AT_PI_COMP')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH_02')},
			{name = 'kolimator', label = _U('component_mounted_scope'), hash = GetHashKey('COMPONENT_AT_PI_RAIL')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP_02')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_brushstroke_camo'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_woodland_camo'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_patriotic'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CAMO')},
			{name = 'magazynek_standardowy', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_02')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_FMJ')},
			{name = 'pociski_grzybkujące', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT')},
			{name = 'pociski_zapalające', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_skull'), hash = GetHashKey('COMPONENT_PISTOL_MK2_CLIP_TRACER')},
		}
	},	
	{
		name = 'WEAPON_COMBATPISTOL',
		label = _U('weapon_combatpistol'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_COMBATPISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_COMBATPISTOL_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER')},
		}
	},
	{
		name = 'WEAPON_APPISTOL',
		label = _U('weapon_appistol'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_APPISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_APPISTOL_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_APPISTOL_VARMOD_LUXE')},
		}
	},
	{name = 'WEAPON_STUNGUN', label = _U('weapon_stungun'), components = {}},
	{
		name = 'WEAPON_PISTOL50',
		label = _U('weapon_pistol50'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_PISTOL50_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_PISTOL50_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_PISTOL50_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_SNSPISTOL',
		label = _U('weapon_snspistol'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_SNSPISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_SNSPISTOL_CLIP_02')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SNSPISTOL_VARMOD_LOWRIDER')},
		}
	},
	{
		name = 'WEAPON_SNSPISTOL_MK2',
		label = _U('weapon_snspistol_mk2'),
		components = {
			{name = 'hamulec_wylotowy', label = _U('component_compensator'), hash = GetHashKey('COMPONENT_AT_PI_COMP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH_03')},
			{name = 'kolimator', label = _U('component_mounted_scope'), hash = GetHashKey('COMPONENT_AT_PI_RAIL_02')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP_02')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_brushstroke_camo'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_woodland_camo'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_patriotic'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CAMO')},
			{name = 'magazynek_standardowy', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_02')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_FMJ')},
			{name = 'pociski_grzybkujące', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT')},
			{name = 'pociski_zapalające', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_skull'), hash = GetHashKey('COMPONENT_SNSPISTOL_MK2_CLIP_TRACER')},
		}
	},	
	{
		name = 'WEAPON_HEAVYPISTOL',
		label = _U('weapon_heavypistol'),
		components = {
			{name = 'magazynek_standardowy', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_HEAVYPISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_HEAVYPISTOL_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_HEAVYPISTOL_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_VINTAGEPISTOL',
		label = _U('weapon_vintagepistol'),
		components = {
			{name = 'magazynek_standardowy', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_VINTAGEPISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_VINTAGEPISTOL_CLIP_02')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP')},
		}
	},
	{name = 'WEAPON_FLAREGUN', label = _U('weapon_flaregun'), components = {}},
	{name = 'WEAPON_MARKSMANPISTOL', label = _U('weapon_marksmanpistol'), components = {}},
	{
		name = 'WEAPON_REVOLVER',
		label = _U('weapon_revolver'),
		components = {
			{name = 'malowanie_złoto', label = _U('malowanie_vip'), hash = GetHashKey('COMPONENT_REVOLVER_VARMOD_BOSS')},
			{name = 'malowanie_gangus', label = _U('malowanie_vip'), hash = GetHashKey('COMPONENT_REVOLVER_VARMOD_GOON')},
		}
	},
	{
		name = 'WEAPON_REVOLVER_MK2',
		label = _U('weapon_revolver_mk2'),
		components = {
			{name = 'hamulec_wylotowy', label = _U('component_compensator'), hash = GetHashKey('COMPONENT_AT_PI_COMP_03')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH')},
			{name = 'celownik_mały', label = _U('component_mounted_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CAMO')},
			{name = 'pociski_standard', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_01')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_FMJ')},
			{name = 'pociski_grzybkujące', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT')},
			{name = 'pociski_zapalające', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_REVOLVER_MK2_CLIP_TRACER')},
		}
	},
	{name = 'WEAPON_DOUBLEACTION', label = _U('weapon_doubleaction'), components = {}},
	{
		name = 'WEAPON_CERAMICPISTOL',
		label = _U('weapon_ceramicpistol'),
		components = {
			{name = 'magazynek_standardowy', label = _U('component_compensator'), hash = GetHashKey('COMPONENT_CERAMICPISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_compensator'), hash = GetHashKey('COMPONENT_CERAMICPISTOL_CLIP_02')},
			{name = 'tłumik', label = _U('component_compensator'), hash = GetHashKey('COMPONENT_CERAMICPISTOL_SUPP')},
		}
	},
	{name = 'WEAPON_NAVYREVOLVER', label = _U('weapon_navyrevolver'), components = {}},
	{name = 'WEAPON_GADGETPISTOL', label = _U('weapon_gadgetpistol'), components = {}},
	{name = 'WEAPON_STUNGUN_MP', label = _U('weapon_stungun_mp'), components = {}}, --DŁUŻSZE ŁADOWANIE JAK NA GTA ONLINE
	{
		name = 'WEAPON_MICROSMG',
		label = _U('weapon_microsmg'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_MICROSMG_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_MICROSMG_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_PI_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_MICROSMG_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_SMG',
		label = _U('weapon_smg'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_SMG_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_SMG_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_SMG_CLIP_03')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_02')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_SMG_MK2',
		label = _U('weapon_smg_mk2'),
		components = {
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'hamulec_wylotowy_płaski', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_MUZZLE_01')},
			{name = 'hamulec_wylotowy_okrągły', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_MUZZLE_02')},
			{name = 'hamulec_wylotowy_duży', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_AT_MUZZLE_03')},
			{name = 'hamulec_wylotowy_długi', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_MUZZLE_04')},
			{name = 'hamulec_wylotowy_inne_zakończenie', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_MUZZLE_05')},
			{name = 'hamulec_wylotowy_duży_płaski', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_MUZZLE_06')},
			{name = 'hamulec_wylotowy_paski', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_MUZZLE_07')},
			{name = 'tłumik', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_PI_SUPP')},
			{name = 'lufa_standard', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_SB_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_SB_BARREL_02')},
			{name = 'celownik_mały', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2')},
			{name = 'celownik_średni', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL_SMG_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_AT_SIGHTS_SMG')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CLIP_02')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CLIP_FMJ')},
			{name = 'pociski_grzybkujące', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT')},
			{name = 'pociski_zapalające', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SMG_MK2_CLIP_TRACER')},

		}
	},
	{
		name = 'WEAPON_ASSAULTSMG',
		label = _U('weapon_assaultsmg'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_ASSAULTSMG_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_ASSAULTSMG_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER')},
		}
	},
	{
		name = 'WEAPON_COMBATPDW',
		label = _U('weapon_combatpdw'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_COMBATPDW_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_COMBATPDW_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_COMBATPDW_CLIP_03')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL')},
		}
	},
	{
		name = 'WEAPON_MACHINEPISTOL',
		label = _U('weapon_machinepistol'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_MACHINEPISTOL_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_MACHINEPISTOL_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_MACHINEPISTOL_CLIP_03')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_PI_SUPP')},
		}
	},
	{
		name = 'WEAPON_MINISMG',
		label = _U('weapon_minismg'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_MINISMG_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_MINISMG_CLIP_02')},
		}
	},
	{
		name = 'WEAPON_PUMPSHOTGUN',
		label = _U('weapon_pumpshotgun'),
		components = {
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_SR_SUPP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER')},
		}
	},
	{
		name = 'WEAPON_PUMPSHOTGUN_MK2',
		label = _U('weapon_pumpshotgun_mk2'),
		components = {
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'hamulec_wylotowy', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_08')},
			{name = 'celownik_mały', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2')},
			{name = 'celownik_średni', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL_MK2')},
			{name = 'celownik_hologramowy', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
			{name = 'tłumik', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SR_SUPP_03')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CAMO')},
			{name = 'naboje_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_01')},
			{name = 'stalowe_loftki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_wybuchowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE')},
			{name = 'pociski_rozpryskowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY')},
		}
	},
	{
		name = 'WEAPON_SAWNOFFSHOTGUN',
		label = _U('weapon_sawnoffshotgun'),
		components = {
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_ASSAULTSHOTGUN',
		label = _U('weapon_assaultshotgun'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_ASSAULTSHOTGUN_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_ASSAULTSHOTGUN_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
		}
	},
	{
		name = 'WEAPON_BULLPUPSHOTGUN',
		label = _U('weapon_bullpupshotgun'),
		components = {
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
		}
	},
	{name = 'WEAPON_MUSKET', label = _U('weapon_musket'), components = {}},
	{
		name = 'WEAPON_HEAVYSHOTGUN',
		label = _U('weapon_heavyshotgun'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_HEAVYSHOTGUN_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_HEAVYSHOTGUN_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_HEAVYSHOTGUN_CLIP_03')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
		}
	},
	{name = 'WEAPON_DBSHOTGUN', label = _U('weapon_dbshotgun'), components = {}},
	{name = 'WEAPON_AUTOSHOTGUN', label = _U('weapon_autoshotgun'), components = {}},
	{
		name = 'WEAPON_COMBATSHOTGUN',
		label = _U('weapon_combatshotgun'),
		components = {
			{name = 'latarka', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
		}
	},
	{
		name = 'WEAPON_ASSAULTRIFLE',
		label = _U('weapon_assaultrifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_CLIP_03')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_ASSAULTRIFLE_MK2',
		label = _U('weapon_assaultrifle_mk2'),
		components = {
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_02')},
			{name = 'pociski_przeciwpancerne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER')},
			{name = 'uchwyt', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP_02')},
			{name = 'lufa_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_BARREL_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'hamulec_wylotowy_płaski', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_01')},
			{name = 'hamulec_wylotowy_taktyczny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_02')},
			{name = 'hamulec_wylotowy_duży_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_03')},
			{name = 'hamulec_wylotowy_precyzyjny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_04')},
			{name = 'hamulec_wylotowy_ciężki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_05')},
			{name = 'hamulec_wylotowy_płaski_otwarty', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_06')},
			{name = 'hamulec_wylotowy_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_07')},
			{name = 'celownik_mały', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2')},
			{name = 'celownik_duży', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
		}
	},
	{
		name = 'WEAPON_CARBINERIFLE',
		label = _U('weapon_carbinerifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_CARBINERIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_CARBINERIFLE_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_box'), hash = GetHashKey('COMPONENT_CARBINERIFLE_CLIP_03')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_CARBINERIFLE_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_CARBINERIFLE_MK2',
		label = _U('weapon_carbinerifle_mk2'),
		components = {
			{name = 'uchwyt', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP_02')},
			{name = 'latarka', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_clip_box'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'lufa_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_CR_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_CR_BARREL_02')},
			{name = 'hamulec_wylotowy_płaski', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_01')},
			{name = 'hamulec_wylotowy_taktyczny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_02')},
			{name = 'hamulec_wylotowy_duży_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_03')},
			{name = 'hamulec_wylotowy_precyzyjny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_04')},
			{name = 'hamulec_wylotowy_ciężki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_05')},
			{name = 'hamulec_wylotowy_płaski_otwarty', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_06')},
			{name = 'hamulec_wylotowy_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_07')},
			{name = 'celownik_mały', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2')},
			{name = 'celownik_duży', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_02')},
			{name = 'pociski_przeciwpancerne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER')},
		}
	},
	{
		name = 'WEAPON_ADVANCEDRIFLE',
		label = _U('weapon_advancedrifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_ADVANCEDRIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_ADVANCEDRIFLE_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_SPECIALCARBINE',
		label = _U('weapon_specialcarbine'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_CLIP_03')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER')},
		}
	},
	{
		name = 'WEAPON_SPECIALCARBINE_MK2',
		label = _U('weapon_specialcarbine_mk2'),
		components = {
			{name = 'uchwyt', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP_02')},
			{name = 'latarka', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_clip_box'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'hamulec_wylotowy_płaski', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_01')},
			{name = 'hamulec_wylotowy_taktyczny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_02')},
			{name = 'hamulec_wylotowy_duży_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_03')},
			{name = 'hamulec_wylotowy_precyzyjny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_04')},
			{name = 'hamulec_wylotowy_ciężki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_05')},
			{name = 'hamulec_wylotowy_płaski_otwarty', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_06')},
			{name = 'hamulec_wylotowy_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_07')},
			{name = 'lufa_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SC_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SC_BARREL_02')},
			{name = 'celownik_mały', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_MK2')},
			{name = 'celownik_duży', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_02')},
			{name = 'pociski_przeciwpancerne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER')},
		}
	},
	{
		name = 'WEAPON_BULLPUPRIFLE',
		label = _U('weapon_bullpuprifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_VARMOD_LOW')},
		}
	},
	{
		name = 'WEAPON_BULLPUPRIFLE_MK2',
		label = _U('weapon_bullpuprifle_mk2'),
		components = {
			{name = 'uchwyt', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP_02')},
			{name = 'latarka', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_clip_box'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'lufa_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_BP_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_BP_BARREL_02')},
			{name = 'hamulec_wylotowy_płaski', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_01')},
			{name = 'hamulec_wylotowy_taktyczny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_02')},
			{name = 'hamulec_wylotowy_duży_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_03')},
			{name = 'hamulec_wylotowy_precyzyjny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_04')},
			{name = 'hamulec_wylotowy_ciężki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_05')},
			{name = 'hamulec_wylotowy_płaski_otwarty', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_06')},
			{name = 'hamulec_wylotowy_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_07')},
			{name = 'celownik_mały', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MACRO_02_MK2')},
			{name = 'celownik_średni', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_02')},
			{name = 'pociski_przeciwpancerne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER')},
		}
	},
	{
		name = 'WEAPON_COMPACTRIFLE',
		label = _U('weapon_compactrifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_COMPACTRIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_COMPACTRIFLE_CLIP_02')},
			{name = 'magazynek_bębenkowy', label = _U('component_clip_drum'), hash = GetHashKey('COMPONENT_COMPACTRIFLE_CLIP_03')},
		}
	},
	{
		name = 'WEAPON_MILITARYRIFLE',
		label = _U('weapon_militaryrifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_MILITARYRIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_MILITARYRIFLE_CLIP_02')},
			{name = 'latarka', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik_średni', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL')},
			{name = 'tłumik', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
		}
	},
	{
		name = 'WEAPON_HEAVYRIFLE',
		label = _U('weapon_heavyrifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_HEAVYRIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_HEAVYRIFLE_CLIP_02')},
			{name = 'latarka', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik_duży', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM')},
			{name = 'tłumik', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'uchwyt', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'malowanie_thefamilies', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_HEAVYRIFLE_CAMO1')},
		}
	},
	{
		name = 'WEAPON_MG',
		label = _U('weapon_mg'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_MG_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_MG_CLIP_02')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL_02')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_MG_VARMOD_LOWRIDER')}
		}
	},
		{
		name = 'WEAPON_COMBATMG',
		label = _U('weapon_combatmg'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_COMBATMG_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_COMBATMG_CLIP_02')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_COMBATMG_VARMOD_LOWRIDER')}
		}
	},
	{
		name = 'WEAPON_COMBATMG_MK2',
		label = _U('weapon_combatmg_mk2'),
		components = {
			{name = 'uchwyt', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP_02')},
			{name = 'lufa_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MG_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_MG_BARREL_02')},
			{name = 'hamulec_wylotowy_płaski', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_01')},
			{name = 'hamulec_wylotowy_taktyczny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_02')},
			{name = 'hamulec_wylotowy_duży_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_03')},
			{name = 'hamulec_wylotowy_precyzyjny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_04')},
			{name = 'hamulec_wylotowy_ciężki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_05')},
			{name = 'hamulec_wylotowy_płaski_otwarty', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_06')},
			{name = 'hamulec_wylotowy_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_07')},
			{name = 'celownik_duży', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2')},
			{name = 'celownik_średni', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_02')},
			{name = 'pociski_przeciwpancerne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_FMJ')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_COMBATMG_MK2_CLIP_TRACER')},
		}
	},
	{
		name = 'WEAPON_GUSENBERG',
		label = _U('weapon_gusenberg'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_GUSENBERG_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_GUSENBERG_CLIP_02')},
		}
	},
	{
		name = 'WEAPON_SNIPERRIFLE',
		label = _U('weapon_sniperrifle'),
		components = {
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_LARGE')},
			{name = 'celownik_zaawansowany', label = _U('component_scope_advanced'), hash = GetHashKey('COMPONENT_AT_SCOPE_MAX')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP_02')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_SNIPERRIFLE_VARMOD_LUXE')},
		}
	},
	{
		name = 'WEAPON_HEAVYSNIPER',
		label = _U('weapon_heavysniper'),
		components = {
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_LARGE')},
			{name = 'celownik_zaawansowany', label = _U('component_scope_advanced'), hash = GetHashKey('COMPONENT_AT_SCOPE_MAX')},
		}
	},
	{
		name = 'WEAPON_HEAVYSNIPER_MK2',
		label = _U('weapon_heavysniper_mk2'),
		components = {
			{name = 'hamulec_wylotowy', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_MUZZLE_08')},
			{name = 'test', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_09')},
			{name = 'celownik_przybliżenie', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_LARGE_MK2')},
			{name = 'celownik_zaawansowany', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MAX')},
			{name = 'celownik_noktowizja', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_NV')},
			{name = 'celownik_termowizja', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_THERMAL')},
			{name = 'lufa_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SR_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SR_BARREL_02')},
			{name = 'tłumik', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SR_SUPP_03')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_02')},
			{name = 'pociski_przeciwpancerne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_wybuchające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE')},
		}
	},
	{
		name = 'WEAPON_MARKSMANRIFLE',
		label = _U('weapon_marksmanrifle'),
		components = {
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_CLIP_02')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM')},
			{name = 'tłumik', label = _U('component_suppressor'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'uchwyt', label = _U('component_grip'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'luksusowe_wykończenie', label = _U('component_luxary_finish'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_VARMOD_LUXE')}
		}
	},
	{
		name = 'WEAPON_MARKSMANRIFLE_MK2',
		label = _U('weapon_marksmanrifle_mk2'),
		components = {
			{name = 'uchwyt', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP_02')},
			{name = 'latarka', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'tłumik', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_AT_AR_SUPP')},
			{name = 'lufa_standard', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MRFL_BARREL_01')},
			{name = 'lufa_ciężka', label = _U('component_scope'), hash = GetHashKey('COMPONENT_AT_MRFL_BARREL_02')},
			{name = 'hamulec_wylotowy_płaski', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_01')},
			{name = 'hamulec_wylotowy_taktyczny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_02')},
			{name = 'hamulec_wylotowy_duży_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_03')},
			{name = 'hamulec_wylotowy_precyzyjny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_04')},
			{name = 'hamulec_wylotowy_ciężki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_05')},
			{name = 'hamulec_wylotowy_płaski_otwarty', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_06')},
			{name = 'hamulec_wylotowy_dziwne_zakończenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_MUZZLE_07')},
			{name = 'celownik_przybliżenie', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2')},
			{name = 'celownik_duży', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_MEDIUM_MK2')},
			{name = 'celownik_holograficzny', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SIGHTS')},
			{name = 'malowanie_wojskowe_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_02')},
			{name = 'malowanie_leśne_kamo', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_03')},
			{name = 'malowanie_czaszki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_04')},
			{name = 'malowanie_diamond_casino', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_05')},
			{name = 'malowanie_znaczki', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_06')},
			{name = 'malowanie_pantera', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_07')},
			{name = 'malowanie_zebra', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_08')},
			{name = 'malowanie_geometryczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_09')},
			{name = 'malowanie_boom', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_10')},
			{name = 'malowanie_patriotyczne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01')},
			{name = 'malowanie_pixele', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CAMO')},
			{name = 'magazynek_standard', label = _U('component_clip_default'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_01')},
			{name = 'magazynek_powiększony', label = _U('component_clip_extended'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_02')},
			{name = 'pociski_przeciwpancerne', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING')},
			{name = 'pociski_pełnopłaszczowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ')},
			{name = 'pociski_zapalające', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY')},
			{name = 'pociski_smugowe', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER')},
		}
	},
	{name = 'WEAPON_RPG', label = _U('weapon_rpg'), components = {}},
	{
		name = 'WEAPON_GRENADELAUNCHER',
		label = _U('weapon_grenadelauncher'),
		components = {
			{name = 'uchwyt', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL')},
		}
	},
	{
		name = 'WEAPON_GRENADELAUNCHER_SMOKE',
		label = _U('weapon_grenadelauncher_smoke'),
		components = {
			{name = 'uchwyt', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_AFGRIP')},
			{name = 'latarka', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_AR_FLSH')},
			{name = 'celownik', label = _U('component_flashlight'), hash = GetHashKey('COMPONENT_AT_SCOPE_SMALL')},
		}
	},
	{name = 'WEAPON_MINIGUN', label = _U('weapon_minigun'), components = {}},
	{name = 'WEAPON_FIREWORK', label = _U('weapon_firework'), components = {}},
	{name = 'WEAPON_HOMINGLAUNCHER', label = _U('weapon_hominglauncher'), components = {}},
	{name = 'WEAPON_COMPACTLAUNCHER', label = _U('weapon_compactlauncher'), components = {}},
	{name = 'WEAPON_EMPLAUNCHER', label = _U('emplauncher'), components = {}},
	{name = 'WEAPON_GRENADE', label = _U('weapon_grenade'), components = {}},
	{name = 'WEAPON_BZGAS', label = _U('weapon_bzgas'), components = {}},
	{name = 'WEAPON_MOLOTOV', label = _U('weapon_molotov'), components = {}},
	{name = 'WEAPON_STICKYBOMB', label = _U('weapon_stickybomb'), components = {}},
	{name = 'WEAPON_PROXMINE', label = _U('weapon_proxmine'), components = {}},
	{name = 'WEAPON_SNOWBALL', label = _U('weapon_snowball'), components = {}},
	{name = 'WEAPON_PIPEBOMB', label = _U('weapon_pipebomb'), components = {}},
	{name = 'WEAPON_BALL', label = _U('weapon_ball'), components = {}},
	{name = 'WEAPON_SMOKEGRENADE', label = _U('weapon_smokegrenade'), components = {}},
	{name = 'WEAPON_FLARE', label = _U('weapon_flare'), components = {}},
	{name = 'WEAPON_PETROLCAN', label = _U('weapon_petrolcan'), components = {}},
	{name = 'GADGET_PARACHUTE', label = _U('gadget_parachute'), components = {}},
	{name = 'WEAPON_FIREEXTINGUISHER', label = _U('weapon_fireextinguisher'), components = {}},
	{name = 'WEAPON_HAZARDCAN', label = _U('weapon_hazardcan'), components = {}},
	{name = 'WEAPON_FERTILIZERCAN', label = _U('weapon_fertilizercan'), components = {}},
}
